name: Laravel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: Copy .env
      run: cp .env.example .env

    - name: Install PHP Dependencies
      run: composer install --no-progress --prefer-dist

    - name: Generate Key
      run: php artisan key:generate

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Node Dependencies
      run: npm install

    - name: Build Vue Assets
      run: npm run build

    - name: Run Tests
      run: php artisan test